[package]
name = "teraformer"
version = "0.3.1"
edition = "2021"

[dependencies]
tera = "1.16"
clap = { version = "3.2", features = ["derive"] }
owo-colors = "3"
serde = "1.0"
thiserror = "1.0"
serde_json = "1.0"
serde_yaml = "0.9"
toml = "0.5"

[profile.release]
opt-level = 3
lto = true
strip = true
codegen-units = 1
panic = 'abort'
