name: Development build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dev_build:
    name: "Development build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          target: x86_64-unknown-linux-gnu
          toolchain: stable
          profile: minimal
          
      - name: Cache 
        uses: actions/cache@v3
        with:
          path: |
            ./target
            ~/.cargo                        
          key: release-${{ runner.os }}-${{ hashFiles('rust-toolchain.toml') }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            release-${{ runner.os }}-${{ hashFiles('rust-toolchain.toml') }}-
            release-${{ runner.os }}-

      - name: Release mode build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target x86_64-unknown-linux-gnu --release --verbose

      - name: Upload release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mudflow
          path: target/x86_64-unknown-linux-gnu/release/mudflow   
  dev_build_release:
    name: Release dev build
    needs: dev_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
      - name: Create release for dev build
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "dev"
          prerelease: true
          title: "Development build"
          files: "./**/*"

