name: Development Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dev_build:
    name: "Development build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          target: x86_64-unknown-linux-gnu
          toolchain: nightly
          profile: minimal
          components: rust-src
          override: true

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose

      - name: Release mode build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --target x86_64-unknown-linux-gnu --release --verbose

      - name: Uppload release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: teraformer
          path: target/x86_64-unknown-linux-gnu/release/teraformer   

